### ISSUE TITLE
1.19.2 Sockets for the undergarden material are broken

### ISSUE THREAD

**Issue by ianwilliamson5** [Syrikal/Tetra-Undergarden-Patch#4]
Simple stuff some of the undergarden materials appear as they are sockets, idk if all of the ones that appear are supposed to be, but they got screwed and now they have no stats associated with them (only sockets the normal stats are fine). they simply grant -1 integrity and no other associated stats

**Comment by Syrikal** [comment]
This is working as intended. Froststeel, Utherium, and Forgotten Metal can be socketed; they provide no stats but do confer a weaker version of their special material abilities. If you're looking at the list of sockets in the holosphere that won't show up.
